# appveyor.yml reference see https://www.appveyor.com/docs/appveyor-yml/

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.5.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# build cache to preserve files/folders between builds
cache:
  - C:\Users\appveyor\.m2

# scripts that run after cloning repository
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      (new-object System.Net.WebClient).DownloadFile(
        'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
        'C:\maven-bin.zip'
      )
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
  - ps: |
      If ($env:Platform -Match "x86") {
        $env:PCRE_PLATFORM="Win32"
        $env:VCVARS_PLATFORM="x86"
        $env:LANG_PLATFORM=""
      } Else {
        $env:PCRE_PLATFORM="x64"
        $env:VCVARS_PLATFORM="amd64"
        $env:LANG_PLATFORM="-x64"
      }
  - cmd: dir "C:\Program Files\Java"
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%PATH%
  - cmd: set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5
  - cmd: SET

#---------------------------------#
#       build configuration       #
#---------------------------------#

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
#build:

# scripts to run before build
#before_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - mvn clean install -DvsBin="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/msbuild.exe" -e

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
#after_build:

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
#before_package:

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'sonar-fsharp-plugin/target/*.jar'
    name: sonar-fsharp-plugin

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

#---------------------------------#
#        global handlers          #
#---------------------------------#

#---------------------------------#
#         notifications           #
#---------------------------------#
